version: '3'

# View organization profile at: https://github.com/joeblew999?preview=true

vars:
  GITHUB_ORG: joeblew999
  # Platform detection
  OS: "{{OS}}"
  ARCH: "{{ARCH}}"
  # Platform-specific extensions
  EXE_EXT: '{{if eq OS "windows"}}.exe{{end}}'
  # Platform-specific binaries
  GH_BINARY: 'gh{{.EXE_EXT}}'
  TERRAFORM_BINARY: 'terraform{{.EXE_EXT}}'
  NATS_BINARY: 'nats{{.EXE_EXT}}'
  # Platform-specific paths
  HOME_DIR: '{{if eq OS "windows"}}{{.USERPROFILE}}{{else}}{{.HOME}}{{end}}'

tasks:
  default:
    desc: List available tasks
    cmds:
      - |
        echo "🛠️  GitHub Organization Setup Tool"
        echo "Platform: {{.OS}}/{{.ARCH}}"
        echo "Organization: {{.GITHUB_ORG}}"
        echo ""
      - task --list

  setup:
    desc: Create .github structure from templates
    cmds:
      - task: clean
      - mkdir -p .github profile
      - go run cmd/github-setup/main.go -org={{.GITHUB_ORG}}

  clean:
    desc: Remove generated .github files
    cmds:
      - rm -rf .github/ISSUE_TEMPLATE .github/issue-templates .github/workflows .github/CODEOWNERS .github/dependabot.yml .github/pull_request_template.md .github/PULL_REQUEST_TEMPLATE

  check:
    desc: Check if generated files are up to date with templates
    cmds:
      - |
        echo "Checking if generated files are up to date..."
        TEMP_DIR=$(mktemp -d)
        go run cmd/github-setup/main.go -org={{.GITHUB_ORG}} -output="$TEMP_DIR"
        if ! diff -r .github "$TEMP_DIR" > /dev/null 2>&1; then
          echo "❌ Generated files are out of date. Run 'task setup' to update."
          rm -rf "$TEMP_DIR"
          exit 1
        else
          echo "✅ Generated files are up to date."
          rm -rf "$TEMP_DIR"
        fi

  install-gh:
    desc: Ensure GitHub CLI is installed (idempotent, cross-platform)
    cmds:
      - |
        echo "📦 Installing GitHub CLI for {{.OS}}/{{.ARCH}}..."
        
        if command -v {{.GH_BINARY}} >/dev/null 2>&1; then
          echo "✅ GitHub CLI already installed: $({{.GH_BINARY}} --version | head -1)"
        else
          echo "📦 Installing GitHub CLI..."
          
          {{if eq .OS "darwin"}}
          # macOS via Homebrew
          if command -v brew >/dev/null 2>&1; then
            brew install gh
          else
            echo "❌ Homebrew not found. Install from: https://brew.sh/"
            exit 1
          fi
          
          {{else if eq .OS "linux"}}
          # Linux via package manager
          if command -v apt >/dev/null 2>&1; then
            # Debian/Ubuntu
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update && sudo apt install gh
          elif command -v yum >/dev/null 2>&1; then
            # RHEL/CentOS/Fedora
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
            sudo yum install gh
          elif command -v pacman >/dev/null 2>&1; then
            # Arch Linux
            sudo pacman -S github-cli
          else
            echo "❌ Unsupported Linux distribution. Install manually: https://cli.github.com/"
            exit 1
          fi
          
          {{else if eq .OS "windows"}}
          # Windows via package manager
          if command -v choco >/dev/null 2>&1; then
            choco install gh
          elif command -v scoop >/dev/null 2>&1; then
            scoop install gh
          elif command -v winget >/dev/null 2>&1; then
            winget install --id GitHub.cli
          else
            echo "❌ No package manager found (choco/scoop/winget). Install from: https://cli.github.com/"
            exit 1
          fi
          
          {{else}}
          echo "❌ Unsupported OS: {{.OS}}. Please install GitHub CLI manually: https://cli.github.com/"
          exit 1
          {{end}}
          
          echo "✅ GitHub CLI installed: $({{.GH_BINARY}} --version | head -1)"
        fi

  verify-github:
    desc: Verify repository state on GitHub matches local templates
    deps: [install-gh]
    cmds:
      - |
        echo "🔍 Verifying GitHub repository state..."
        
        # Check if repo exists and is accessible
        if ! gh repo view {{.GITHUB_ORG}}/.github >/dev/null 2>&1; then
          echo "❌ Cannot access repository {{.GITHUB_ORG}}/.github"
          exit 1
        fi
        
        echo "✅ Repository {{.GITHUB_ORG}}/.github is accessible"
        
        # Check if workflows are enabled
        echo "📋 Checking workflows..."
        gh workflow list --repo {{.GITHUB_ORG}}/.github
        
        # Check if issues/PRs use our templates
        echo "📝 Checking if templates are active..."
        echo "  Issue templates:"
        gh api repos/{{.GITHUB_ORG}}/.github/contents/.github/ISSUE_TEMPLATE --jq '.[].name' 2>/dev/null || \
        gh api repos/{{.GITHUB_ORG}}/.github/contents/.github/issue-templates --jq '.[].name' 2>/dev/null || \
        echo "    No issue templates found"
        
        # Check organization profile
        echo "🏢 Organization profile:"
        gh api orgs/{{.GITHUB_ORG}} --jq '.name // .login' 2>/dev/null || \
        echo "    Organization API requires admin:org scope"
        
        # Check if dependabot is configured
        echo "🤖 Checking Dependabot configuration..."
        if gh api repos/{{.GITHUB_ORG}}/.github/contents/.github/dependabot.yml >/dev/null 2>&1; then
          echo "✅ Dependabot configuration found"
        else
          echo "❌ Dependabot configuration not found"
        fi
        
        echo "✅ GitHub verification complete"

  validate-all:
    desc: Run all validation checks (local + GitHub)
    cmds:
      - task: check
      - task: verify-github

  status:
    desc: Show current system status and health
    cmds:
      - |
        echo "🏢 GitHub Organization: {{.GITHUB_ORG}}"
        echo "📁 Repository: https://github.com/{{.GITHUB_ORG}}/.github"
        echo "🌍 Platform: {{.OS}}/{{.ARCH}}"
        echo ""
        echo "📊 System Status:"
        
        # Check if files are generated
        if [ -d ".github" ]; then
          echo "✅ Generated files exist"
        else
          echo "❌ Generated files missing - run 'task setup'"
        fi
        
        # Check if files are up to date (quick check)
        if task check >/dev/null 2>&1; then
          echo "✅ Generated files are up to date"
        else
          echo "⚠️  Generated files may be out of date - run 'task check' for details"
        fi
        
        # Check Go module
        if go mod verify >/dev/null 2>&1; then
          echo "✅ Go module verified"
        else
          echo "❌ Go module issues - run 'go mod tidy'"
        fi
        
        # Platform-aware GitHub CLI check
        if command -v {{.GH_BINARY}} >/dev/null 2>&1; then
          echo "✅ GitHub CLI available: $({{.GH_BINARY}} --version | head -1 | cut -d' ' -f3)"
        else
          echo "❌ GitHub CLI not installed - run 'task install-gh'"
        fi
        
        # Platform-specific checks
        {{if eq .OS "darwin"}}
        # macOS specific checks
        if command -v brew >/dev/null 2>&1; then
          echo "✅ Homebrew available"
        else
          echo "⚠️  Homebrew not installed (recommended for macOS)"
        fi
        {{else if eq .OS "linux"}}
        # Linux specific checks
        if systemctl --version >/dev/null 2>&1; then
          echo "✅ Systemd available"
        else
          echo "ℹ️  Systemd not available (using alternative service management)"
        fi
        {{else if eq .OS "windows"}}
        # Windows specific checks  
        if command -v choco >/dev/null 2>&1; then
          echo "✅ Chocolatey available"
        elif command -v scoop >/dev/null 2>&1; then
          echo "✅ Scoop available"
        elif command -v winget >/dev/null 2>&1; then
          echo "✅ Winget available"
        else
          echo "⚠️  No package manager found (consider installing Chocolatey/Scoop/Winget)"
        fi
        {{end}}

  dev:
    desc: Development workflow - clean, setup, and check
    cmds:
      - echo "🚀 Running development workflow..."
      - task: clean
      - task: setup
      - task: check
      - echo "✅ Development workflow complete"

  help:
    desc: Show detailed help and usage examples
    cmds:
      - |
        echo "🛠️  GitHub Organization Setup Tool"
        echo "=================================="
        echo ""
        echo "📋 Quick Start:"
        echo "  task setup     # Generate all files"
        echo "  task status    # Check system health"
        echo "  task dev       # Development workflow"
        echo ""
        echo "🔍 Validation:"
        echo "  task check           # Check local files vs templates"
        echo "  task verify-github   # Check GitHub state"
        echo "  task validate-all    # Run all checks"
        echo ""
        echo "🧹 Maintenance:"
        echo "  task clean       # Remove generated files"
        echo "  task install-gh  # Install GitHub CLI"
        echo ""
        echo "🚀 NATS Integration:"
        echo "  task nats-monitor        # Monitor NATS-powered workflows"
        echo "  task nats-deploy         # Deploy NATS infrastructure"
        echo "  task nats-scale          # Scale NATS infrastructure"
        echo "  task nats-controller     # Run NATS controller locally"
        echo ""
        echo "🌍 Cross-Platform:"
        echo "  task test-platform       # Test cross-platform compatibility"
        echo "  Platform: {{.OS}}/{{.ARCH}}   # Current platform"
        echo ""
        echo "📖 Documentation:"
        echo "  README.md        # Architecture and patterns"
        echo "  CONTRIBUTING.md  # Contribution guidelines"
        echo ""
        echo "🌐 Links:"
        echo "  Repository: https://github.com/{{.GITHUB_ORG}}/.github"
        echo "  Profile:    https://github.com/{{.GITHUB_ORG}}?preview=true"
        echo "  Workflows:  https://github.com/{{.GITHUB_ORG}}/.github/actions"

  monitor-workflow:
    desc: Monitor GitHub Actions workflow execution
    cmds:
      - |
        echo "🔍 Monitoring GitHub Actions workflow for template changes..."
        echo "This script monitors the full cycle: template change → GitHub Actions → file regeneration"
        echo ""
        ./monitor-workflow.sh

  monitor-nats:
    desc: Monitor workflow using NATS (requires NATS server)
    cmds:
      - |
        echo "🚀 NATS-enhanced workflow monitoring"
        echo "This demonstrates advanced patterns for workflow orchestration"
        echo ""
        ./nats-monitor.sh check

  nats-demo:
    desc: Show NATS enhanced workflow capabilities
    cmds:
      - |
        echo "🌟 NATS Enhanced GitHub Workflow Demonstration"
        echo "=============================================="
        echo ""
        ./nats-monitor.sh demo

  nats-controller:
    desc: Start the NATS-based workflow controller (requires NATS server)
    cmds:
      - |
        echo "🎛️  Starting NATS workflow controller..."
        go mod download
        go run cmd/nats-controller/main.go

  nats-monitor:
    desc: Monitor NATS-powered GitHub workflows
    cmds:
      - |
        echo "🔍 NATS Workflow Monitor for {{.GITHUB_ORG}}"
        echo "==========================================="
        
        if [ -f "nats-monitor.sh" ]; then
          chmod +x nats-monitor.sh
          ./nats-monitor.sh
        else
          echo "❌ nats-monitor.sh not found"
          echo "   This would connect to Synadia Cloud and monitor:"
          echo "   • github.{{.GITHUB_ORG}}.template_changed"
          echo "   • github.{{.GITHUB_ORG}}.workflow_status"
          echo "   • github.{{.GITHUB_ORG}}.regeneration_requested"
          echo ""
          echo "   To enable NATS monitoring:"
          echo "   1. Sign up for Synadia Cloud"
          echo "   2. Configure credentials"
          echo "   3. Run: task nats-deploy"
        fi

  nats-deploy:
    desc: Deploy NATS infrastructure using Terraform
    cmds:
      - |
        echo "🚀 Deploying NATS Infrastructure"
        echo "================================"
        
        if ! command -v terraform >/dev/null 2>&1; then
          echo "❌ Terraform not installed"
          echo "   Install from: https://www.terraform.io/downloads"
          exit 1
        fi
        
        cd terraform
        
        echo "📋 Initializing Terraform..."
        terraform init
        
        echo "📋 Planning NATS infrastructure..."
        terraform plan -var="github_org={{.GITHUB_ORG}}"
        
        echo ""
        echo "To apply:"
        echo "  cd terraform && terraform apply -var='github_org={{.GITHUB_ORG}}'"

  nats-scale:
    desc: Scale NATS infrastructure based on load
    cmds:
      - |
        echo "📈 NATS Infrastructure Scaling"
        echo "=============================="
        
        echo "This would:"
        echo "1. Check current GitHub event load"
        echo "2. Analyze NATS queue depths"
        echo "3. Trigger Terraform for additional capacity"
        echo "4. Auto-configure new NATS nodes"
        echo ""
        echo "Example scaling triggers:"
        echo "• Queue depth > 1000 messages"
        echo "• Processing latency > 30 seconds"
        echo "• GitHub API rate limit approaching"
        echo ""
        echo "Self-similar pattern: NATS controllers deploy more NATS!"

  nats-controller:
    desc: Run NATS controller locally for development
    cmds:
      - |
        echo "🤖 Starting Local NATS Controller"
        echo "================================="
        
        if [ ! -f "cmd/nats-controller/main.go" ]; then
          echo "❌ NATS controller not found"
          exit 1
        fi
        
        echo "📋 Environment:"
        echo "  GITHUB_ORG: {{.GITHUB_ORG}}"
        echo "  NATS_URL: ${NATS_URL:-nats://localhost:4222}"
        echo ""
        
        if ! command -v {{.NATS_BINARY}} >/dev/null 2>&1; then
          echo "⚠️  NATS CLI not installed"
          echo "   Install from: https://github.com/nats-io/natscli"
          echo "   Or use Docker: docker run natsio/nats-server"
        fi
        
        echo "🚀 Starting controller..."
        go run cmd/nats-controller/main.go

  test-platform:
    desc: Test cross-platform compatibility
    cmds:
      - |
        echo "🧪 Cross-Platform Compatibility Test"
        echo "===================================="
        echo "Platform: {{.OS}}/{{.ARCH}}"
        echo "Home Dir: {{.HOME_DIR}}"
        echo ""
        
        echo "📋 Binary Checks:"
        echo "  Go: $(go version)"
        
        {{if eq .OS "windows"}}
        echo "  PowerShell: $(if (Get-Command powershell -ErrorAction SilentlyContinue) { 'Available' } else { 'Not Available' })"
        echo "  Git: $(git --version)"
        {{else}}
        echo "  Shell: $SHELL"
        echo "  Git: $(git --version)"
        {{end}}
        
        echo ""
        echo "📁 Path Tests:"
        echo "  Current Dir: $(pwd)"
        echo "  Temp Dir: {{if eq .OS "windows"}}%TEMP%{{else}}/tmp{{end}}"
        
        echo ""
        echo "🔧 Platform Features:"
        {{if eq .OS "darwin"}}
        echo "  ✅ macOS Homebrew integration"
        echo "  ✅ Keychain credential storage"
        echo "  ✅ Spotlight file indexing"
        {{else if eq .OS "linux"}}
        echo "  ✅ Linux package manager support"
        echo "  ✅ Systemd service integration"
        echo "  ✅ Container compatibility"
        {{else if eq .OS "windows"}}
        echo "  ✅ Windows package manager support"
        echo "  ✅ Windows Services integration"
        echo "  ✅ PowerShell and CMD compatibility"
        {{end}}
        
        echo ""
        echo "🔍 Testing core operations..."
        
        # Test template generation
        if go run cmd/github-setup/main.go -version >/dev/null 2>&1; then
          echo "  ✅ Template processor works"
        else
          echo "  ❌ Template processor failed"
        fi
        
        # Test GitHub CLI
        if command -v {{.GH_BINARY}} >/dev/null 2>&1; then
          echo "  ✅ GitHub CLI available"
        else
          echo "  ⚠️  GitHub CLI not installed"
        fi
        
        echo ""
        echo "✅ Platform compatibility test complete!"