version: '3'

# View organization profile at: https://github.com/joeblew999?preview=true

vars:
  GITHUB_ORG: joeblew999

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Create .github structure from templates
    cmds:
      - mkdir -p .github profile
      - go run cmd/github-setup/main.go -org={{.GITHUB_ORG}}

  clean:
    desc: Remove generated .github files
    cmds:
      - rm -rf .github/ISSUE_TEMPLATE .github/issue-templates .github/workflows .github/CODEOWNERS .github/dependabot.yml .github/pull_request_template.md

  check:
    desc: Check if generated files are up to date with templates
    cmds:
      - |
        echo "Checking if generated files are up to date..."
        TEMP_DIR=$(mktemp -d)
        go run cmd/github-setup/main.go -org={{.GITHUB_ORG}} -output="$TEMP_DIR"
        if ! diff -r .github "$TEMP_DIR" > /dev/null 2>&1; then
          echo "❌ Generated files are out of date. Run 'task setup' to update."
          rm -rf "$TEMP_DIR"
          exit 1
        else
          echo "✅ Generated files are up to date."
          rm -rf "$TEMP_DIR"
        fi